FROM node:20-alpine

WORKDIR /app

COPY . .

RUN corepack enable \
  && pnpm install --frozen-lockfile \
  && pnpm --filter @mlbb/shared build \
  && pnpm --filter @mlbb/db build \
  && pnpm --filter @mlbb/api build

ENV NODE_ENV=production
EXPOSE 8787

WORKDIR /app/apps/api

CMD ["node", "dist/index.js"]
